services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 2g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  data_index:
    container_name: data_index
    build: ./app
    depends_on:
      - elasticsearch

  backend:
    container_name: backend
    ports:
      - "8080:8080"
    build: ./backend
    depends_on:
      - data_index

  frontend:
    container_name: frontend
    ports:
      - "80:80"
    build: ./frontend
    depends_on:
      - backend

volumes:
  es_data:
    driver: local
