export const languageOptions = [
    { value: "Python", label: "Python" },
    { value: "JavaScript", label: "JavaScript" },
    { value: "Java", label: "Java" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "C++", label: "C++" },
    { value: "Go", label: "Go" },
    { value: "C", label: "C" },
    { value: "C#", label: "C#" },
    { value: "PHP", label: "PHP" },
    { value: "HTML", label: "HTML" },
    { value: "Shell", label: "Shell" },
    { value: "Objective-C", label: "Objective-C" },
    { value: "Ruby", label: "Ruby" },
    { value: "Jupyter Notebook", label: "Jupyter Notebook" },
    { value: "Swift", label: "Swift" },
    { value: "Rust", label: "Rust" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "CSS", label: "CSS" },
    { value: "Vue", label: "Vue" },
    { value: "Dart", label: "Dart" },
    { value: "Lua", label: "Lua" },
    { value: "Scala", label: "Scala" },
    { value: "R", label: "R" },
    { value: "PowerShell", label: "PowerShell" },
    { value: "Clojure", label: "Clojure" },
    { value: "Emacs Lisp", label: "Emacs Lisp" },
    { value: "TeX", label: "TeX" },
    { value: "Elixir", label: "Elixir" },
    { value: "Haskell", label: "Haskell" },
    { value: "SCSS", label: "SCSS" },
    { value: "CoffeeScript", label: "CoffeeScript" },
    { value: "Perl", label: "Perl" },
    { value: "Dockerfile", label: "Dockerfile" },
    { value: "Julia", label: "Julia" },
    { value: "Vim script", label: "Vim script" }, // Note: "Vim Script" appeared twice, kept as "Vim script" for consistency
    { value: "Makefile", label: "Makefile" },
    { value: "Assembly", label: "Assembly" },
    { value: "Erlang", label: "Erlang" },
    { value: "MATLAB", label: "MATLAB" }, // Note: "Matlab" also appeared, standardized to "MATLAB"
    { value: "HCL", label: "HCL" },
    { value: "Solidity", label: "Solidity" },
    { value: "Groovy", label: "Groovy" },
    { value: "OCaml", label: "OCaml" },
    { value: "Svelte", label: "Svelte" },
    { value: "Pascal", label: "Pascal" },
    { value: "GDScript", label: "GDScript" },
    { value: "Batchfile", label: "Batchfile" },
    { value: "Common Lisp", label: "Common Lisp" },
    { value: "F#", label: "F#" },
    { value: "Verilog", label: "Verilog" },
    { value: "Nim", label: "Nim" },
    { value: "CMake", label: "CMake" },
    { value: "Nix", label: "Nix" },
    { value: "Jinja", label: "Jinja" },
    { value: "ShaderLab", label: "ShaderLab" },
    { value: "Cuda", label: "Cuda" },
    { value: "VimL", label: "VimL" },
    { value: "GLSL", label: "GLSL" },
    { value: "ActionScript", label: "ActionScript" },
    { value: "Elm", label: "Elm" },
    { value: "PLpgSQL", label: "PLpgSQL" },
    { value: "Roff", label: "Roff" },
    { value: "Less", label: "Less" },
    { value: "Vala", label: "Vala" },
    { value: "Objective-C++", label: "Objective-C++" },
    { value: "AutoHotkey", label: "AutoHotkey" },
    { value: "MDX", label: "MDX" },
    { value: "QML", label: "QML" },
    { value: "Scheme", label: "Scheme" },
    { value: "Crystal", label: "Crystal" },
    { value: "D", label: "D" },
    { value: "TSQL", label: "TSQL" },
    { value: "Zig", label: "Zig" },
    { value: "Fortran", label: "Fortran" }, // Note: "FORTRAN" also appeared, standardized to "Fortran"
    { value: "Haxe", label: "Haxe" },
    { value: "VHDL", label: "VHDL" },
    { value: "Rich Text Format", label: "Rich Text Format" },
    { value: "XSLT", label: "XSLT" },
    { value: "HLSL", label: "HLSL" },
    { value: "OpenSCAD", label: "OpenSCAD" },
    { value: "Markdown", label: "Markdown" },
    { value: "Processing", label: "Processing" },
    { value: "EJS", label: "EJS" },
    { value: "Mathematica", label: "Mathematica" },
    { value: "Tcl", label: "Tcl" },
    { value: "Blade", label: "Blade" },
    { value: "Visual Basic .NET", label: "Visual Basic .NET" },
    { value: "Pug", label: "Pug" },
    { value: "Racket", label: "Racket" },
    { value: "Smarty", label: "Smarty" },
    { value: "SystemVerilog", label: "SystemVerilog" },
    { value: "Stylus", label: "Stylus" },
    { value: "Astro", label: "Astro" },
    { value: "Handlebars", label: "Handlebars" },
    { value: "Starlark", label: "Starlark" },
    { value: "Cython", label: "Cython" },
    { value: "Mustache", label: "Mustache" },
    { value: "PureScript", label: "PureScript" },
    { value: "YARA", label: "YARA" },
    { value: "ASL", label: "ASL" },
    { value: "AppleScript", label: "AppleScript" },
    { value: "PostScript", label: "PostScript" },
    { value: "Coq", label: "Coq" },
    { value: "Nunjucks", label: "Nunjucks" },
    { value: "Arduino", label: "Arduino" },
    { value: "Bikeshed", label: "Bikeshed" },
    { value: "WebAssembly", label: "WebAssembly" },
    { value: "Apex", label: "Apex" },
    { value: "AutoIt", label: "AutoIt" },
    { value: "Reason", label: "Reason" },
    { value: "Standard ML", label: "Standard ML" },
    { value: "OpenEdge ABL", label: "OpenEdge ABL" },
    { value: "LLVM", label: "LLVM" },
    { value: "Prolog", label: "Prolog" },
    { value: "Visual Basic", label: "Visual Basic" },
    { value: "ReScript", label: "ReScript" },
    { value: "VBA", label: "VBA" },
    { value: "Jsonnet", label: "Jsonnet" },
    { value: "G-code", label: "G-code" },
    { value: "Smali", label: "Smali" },
    { value: "FreeMarker", label: "FreeMarker" },
    { value: "Gherkin", label: "Gherkin" },
    { value: "Hack", label: "Hack" },
    { value: "Sass", label: "Sass" },
    { value: "Adblock Filter List", label: "Adblock Filter List" },
    { value: "Awk", label: "Awk" },
    { value: "Bicep", label: "Bicep" },
    { value: "Max", label: "Max" },
    { value: "Agda", label: "Agda" },
    { value: "ApacheConf", label: "ApacheConf" },
    { value: "LiveScript", label: "LiveScript" },
    { value: "PLSQL", label: "PLSQL" },
    { value: "Puppet", label: "Puppet" },
    { value: "Classic ASP", label: "Classic ASP" },
    { value: "Forth", label: "Forth" },
    { value: "Idris", label: "Idris" },
    { value: "Inno Setup", label: "Inno Setup" },
    { value: "Liquid", label: "Liquid" },
    { value: "SourcePawn", label: "SourcePawn" },
    { value: "Twig", label: "Twig" },
    { value: "Fennel", label: "Fennel" },
    { value: "V", label: "V" },
    { value: "YAML", label: "YAML" },
    { value: "AGS Script", label: "AGS Script" },
    { value: "ASP", label: "ASP" },
    { value: "Eagle", label: "Eagle" },
    { value: "Lean", label: "Lean" },
    { value: "Logos", label: "Logos" },
    { value: "Open Policy Agent", label: "Open Policy Agent" },
    { value: "Smalltalk", label: "Smalltalk" },
    { value: "VBScript", label: "VBScript" },
    { value: "1C Enterprise", label: "1C Enterprise" },
    { value: "NSIS", label: "NSIS" },
    { value: "ABAP", label: "ABAP" },
    { value: "Ada", label: "Ada" },
    { value: "TLA", label: "TLA" },
    { value: "VCL", label: "VCL" },
    { value: "BitBake", label: "BitBake" },
    { value: "Brainfuck", label: "Brainfuck" },
    { value: "GCC Machine Description", label: "GCC Machine Description" },
    { value: "KiCad", label: "KiCad" }, // Note: "KiCad Layout" also appeared, standardized to "KiCad"
    { value: "PureBasic", label: "PureBasic" },
    { value: "SQL", label: "SQL" },
    { value: "SWIG", label: "SWIG" },
    { value: "Yacc", label: "Yacc" },
    { value: "AngelScript", label: "AngelScript" },
    { value: "CartoCSS", label: "CartoCSS" },
    { value: "DM", label: "DM" },
    { value: "GAP", label: "GAP" },
    { value: "Groff", label: "Groff" },
    { value: "MQL5", label: "MQL5" },
    { value: "Nginx", label: "Nginx" },
    { value: "Raku", label: "Raku" },
    { value: "SaltStack", label: "SaltStack" },
    { value: "ANTLR", label: "ANTLR" },
    { value: "ColdFusion", label: "ColdFusion" },
    { value: "Game Maker Language", label: "Game Maker Language" },
    { value: "JetBrains MPS", label: "JetBrains MPS" },
    { value: "SMT", label: "SMT" },
    { value: "Stata", label: "Stata" },
    { value: "Vim Snippet", label: "Vim Snippet" },
    { value: "Cairo", label: "Cairo" },
    { value: "Dhall", label: "Dhall" },
    { value: "F*", label: "F*" },
    { value: "Gnuplot", label: "Gnuplot" },
    { value: "Isabelle", label: "Isabelle" },
    { value: "KiCad Layout", label: "KiCad Layout" },
    { value: "Lex", label: "Lex" },
    { value: "M", label: "M" },
    { value: "M4", label: "M4" },
    { value: "MoonScript", label: "MoonScript" },
    { value: "NASL", label: "NASL" },
    { value: "Nextflow", label: "Nextflow" },
    { value: "Ren'Py", label: "Ren'Py" },
    { value: "RobotFramework", label: "RobotFramework" },
    { value: "RouterOS Script", label: "RouterOS Script" },
    { value: "SQF", label: "SQF" },
    { value: "Squirrel", label: "Squirrel" },
    { value: "SuperCollider", label: "SuperCollider" },
    { value: "Visual Basic 6.0", label: "Visual Basic 6.0" },
    { value: "ZenScript", label: "ZenScript" },
    { value: "nesC", label: "nesC" },
    { value: "q", label: "q" },
    { value: "ATS", label: "ATS" },
    { value: "BlitzBasic", label: "BlitzBasic" },
    { value: "COBOL", label: "COBOL" },
    { value: "Cirru", label: "Cirru" },
    { value: "CodeQL", label: "CodeQL" },
    { value: "Fluent", label: "Fluent" },
    { value: "Gosu", label: "Gosu" },
    { value: "HolyC", label: "HolyC" },
    { value: "Just", label: "Just" }, // Note: "just" also appeared, standardized to "Just"
    { value: "Lasso", label: "Lasso" },
    { value: "MLIR", label: "MLIR" },
    { value: "MQL4", label: "MQL4" },
    { value: "Metal", label: "Metal" },
    { value: "Modelica", label: "Modelica" },
    { value: "Move", label: "Move" },
    { value: "Odin", label: "Odin" },
    { value: "POV-Ray SDL", label: "POV-Ray SDL" },
    { value: "Pawn", label: "Pawn" },
    { value: "Pony", label: "Pony" },
    { value: "RAML", label: "RAML" },
    { value: "RMarkdown", label: "RMarkdown" },
    { value: "SQLPL", label: "SQLPL" },
    { value: "XML", label: "XML" },
    { value: "Xtend", label: "Xtend" },
    { value: "ZIL", label: "ZIL" },
    { value: "jq", label: "jq" },
    { value: "AL", label: "AL" },
    { value: "AMPL", label: "AMPL" },
    { value: "ASP.NET", label: "ASP.NET" },
    { value: "Arc", label: "Arc" },
    { value: "AsciiDoc", label: "AsciiDoc" },
    { value: "Bluespec", label: "Bluespec" },
    { value: "CUE", label: "CUE" },
    { value: "Common Workflow Language", label: "Common Workflow Language" },
    { value: "Csound Document", label: "Csound Document" },
    { value: "DIGITAL Command Language", label: "DIGITAL Command Language" },
    { value: "FreeBasic", label: "FreeBasic" },
    { value: "Gleam", label: "Gleam" },
    { value: "Haml", label: "Haml" },
    { value: "Hosts File", label: "Hosts File" },
    { value: "Ink", label: "Ink" },
    { value: "JSON", label: "JSON" },
    { value: "Macaulay2", label: "Macaulay2" },
    { value: "Mako", label: "Mako" },
    { value: "Mermaid", label: "Mermaid" },
    { value: "Modula-3", label: "Modula-3" },
    { value: "NCL", label: "NCL" },
    { value: "Nemerle", label: "Nemerle" },
    { value: "Objective-J", label: "Objective-J" },
    { value: "OpenQASM", label: "OpenQASM" },
    { value: "Protocol Buffer", label: "Protocol Buffer" },
    { value: "Q#", label: "Q#" },
    { value: "QMake", label: "QMake" },
    { value: "REXX", label: "REXX" },
    { value: "Ragel", label: "Ragel" },
    { value: "SVG", label: "SVG" },
    { value: "Slash", label: "Slash" },
    { value: "Slim", label: "Slim" },
    { value: "TL-Verilog", label: "TL-Verilog" },
    { value: "Terra", label: "Terra" },
    { value: "UnrealScript", label: "UnrealScript" },
    { value: "Zeek", label: "Zeek" },
    { value: "mcfunction", label: "mcfunction" },
    { value: "reStructuredText", label: "reStructuredText" },
    { value: "sed", label: "sed" },
    { value: "APL", label: "APL" },
    { value: "Augeas", label: "Augeas" },
    { value: "BASIC", label: "BASIC" },
    { value: "Ballerina", label: "Ballerina" },
    { value: "Bison", label: "Bison" },
    { value: "Boo", label: "Boo" },
    { value: "Boogie", label: "Boogie" },
    { value: "Brightscript", label: "Brightscript" },
    { value: "CAP CDS", label: "CAP CDS" },
    { value: "Cadence", label: "Cadence" },
    { value: "Chapel", label: "Chapel" },
    { value: "ChucK", label: "ChucK" },
    { value: "Circom", label: "Circom" },
    { value: "Component Pascal", label: "Component Pascal" },
    { value: "Cycript", label: "Cycript" },
    { value: "D2", label: "D2" },
    { value: "DCPU-16 ASM", label: "DCPU-16 ASM" },
    { value: "Dafny", label: "Dafny" },
    { value: "Delphi", label: "Delphi" },
    { value: "Dylan", label: "Dylan" },
    { value: "Earthly", label: "Earthly" },
    { value: "Eiffel", label: "Eiffel" },
    { value: "Fancy", label: "Fancy" },
    { value: "Frege", label: "Frege" },
    { value: "Futhark", label: "Futhark" },
    { value: "GAMS", label: "GAMS" },
    { value: "GSC", label: "GSC" },
    { value: "Gettext Catalog", label: "Gettext Catalog" },
    { value: "Grammatical Framework", label: "Grammatical Framework" },
    { value: "HyPhy", label: "HyPhy" },
    { value: "IDL", label: "IDL" },
    { value: "Inform 7", label: "Inform 7" },
    { value: "Io", label: "Io" },
    { value: "Janet", label: "Janet" },
    { value: "Jasmin", label: "Jasmin" },
    { value: "Kaitai Struct", label: "Kaitai Struct" },
    { value: "KakouneScript", label: "KakouneScript" },
    { value: "LabVIEW", label: "LabVIEW" },
    { value: "LilyPond", label: "LilyPond" },
    { value: "LoomScript", label: "LoomScript" },
    { value: "Mask", label: "Mask" },
    { value: "Mercury", label: "Mercury" },
    { value: "Meson", label: "Meson" },
    { value: "Modula-2", label: "Modula-2" },
    { value: "Monkey C", label: "Monkey C" },
    { value: "Motoko", label: "Motoko" },
    { value: "NewLisp", label: "NewLisp" },
    { value: "Nimrod", label: "Nimrod" },
    { value: "Nushell", label: "Nushell" },
    { value: "Org", label: "Org" },
    { value: "Oz", label: "Oz" },
    { value: "P4", label: "P4" },
    { value: "PEG.js", label: "PEG.js" },
    { value: "Parrot", label: "Parrot" },
    { value: "Perl 6", label: "Perl 6" }, // Note: "Perl6" also appeared, standardized to "Perl 6"
    { value: "PicoLisp", label: "PicoLisp" },
    { value: "PlantUML", label: "PlantUML" },
    { value: "PogoScript", label: "PogoScript" },
    { value: "Portugol", label: "Portugol" },
    { value: "Propeller Spin", label: "Propeller Spin" },
    { value: "Qt Script", label: "Qt Script" },
    { value: "REALbasic", label: "REALbasic" },
    { value: "RPC", label: "RPC" },
    { value: "RPM Spec", label: "RPM Spec" },
    { value: "Rascal", label: "Rascal" },
    { value: "SAS", label: "SAS" },
    { value: "SRecode Template", label: "SRecode Template" },
    { value: "Sage", label: "Sage" },
    { value: "Scilab", label: "Scilab" },
    { value: "Self", label: "Self" },
    { value: "Shen", label: "Shen" },
    { value: "Stan", label: "Stan" },
    { value: "Text", label: "Text" },
    { value: "Thrift", label: "Thrift" },
    { value: "Turing", label: "Turing" },
    { value: "Typst", label: "Typst" },
    { value: "Uno", label: "Uno" },
    { value: "Valve Data Format", label: "Valve Data Format" },
    { value: "Web Ontology Language", label: "Web Ontology Language" },
    { value: "Wikitext", label: "Wikitext" },
    { value: "YASnippet", label: "YASnippet" },
    { value: "eC", label: "eC" },
    { value: "hoon", label: "hoon" },
  ];
  